MULE-13487: In unmarshaller, make errorLimitCounter customizable.
javaee/jaxb-v2 pull request #1154
Opened 2017-11-02 13:50 UTC by facundovs

2017-12-05 17:15 UTC, aiannucci commented
@bravehorsie or someone with access, any chance to review this? Fixes #1139 
Thanks!

2018-02-08 11:21 UTC, lucalas commented
@bravehorsie are there any news about it?

2018-02-20 18:36 UTC, taz77 commented
Took a lot of searching to find this, but this problem causes some of the code I work on to stop throwing errors when it should be. We test for proper errors being handled. Would be great if this PR could get reviewed and merged.

2018-06-28 13:04 UTC, matteobaccan commented
Any news about this merge?

2018-08-02 11:42 UTC, taz77 commented
@bravehorsie I see you are a committer on this project. Can this PR get some attention? This continues to be a problem with JAXB that has not been resolved.

2018-08-03 09:05 UTC, bravehorsie requested changes
Besides comments in code please also fix copyright years in updated files and add copyright headers to files that were created.

After fixing comments above, the change looks good, thank you @facundovs !

If you want this PR to be accepted you need to sign http://www.oracle.com/technetwork/community/oca-486395.html

2018-09-04 12:58 UTC, lucalas commented
@facundovs please can you fix reported issues?

2026-02-26 22:55 UTC, closed without merging